package app

const (
	RULE_KEY_SEPARATOR = "."

	RULE_TYPE_MATCH       = "MATCH"
	RULE_TYPE_NOT_MATCH   = "NOT_MATCH"
	RULE_TYPE_PATTERN     = "PATTERN"
	RULE_TYPE_NOT_PATTERN = "NOT_PATTERN"
)

const (
	SIGN_METHOD_SHA1     = "SHA1"
	SIGN_METHOD_SHA256   = "SHA256"
	SIGN_METHOD_MD5      = "MD5"
	SIGN_METHOD_PKCS1V15 = "PKCS1V15"
	SIGN_METHOD_PSS      = "PSS"

	PUB_KEY_TYPE_PKCS1 = "PKCS1"
	PUB_KEY_TYPE_PKIX  = "PKIX"
)

const (
	DELAY_TYPE_FIXED = "FIXED"
	DELAY_TYPE_RANGE = "RANGE"
)
